"""empty message

Revision ID: c8e4ef439ceb
Revises: e7a061c641d2
Create Date: 2020-03-13 15:21:31.922398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e4ef439ceb'
down_revision = 'e7a061c641d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(length=2048), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('answer_ibfk_2', 'answer', type_='foreignkey')
    op.drop_constraint('answer_ibfk_1', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answer', 'user', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('question_ibfk_1', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'user', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_ibfk_1', 'question', 'user', ['author_id'], ['id'])
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_ibfk_1', 'answer', 'user', ['author_id'], ['id'])
    op.create_foreign_key('answer_ibfk_2', 'answer', 'question', ['question_id'], ['id'])
    op.drop_table('comment')
    # ### end Alembic commands ###
